{"name": "test_second_case[True-second_create_project-False]", "status": "failed", "statusDetails": {"message": "AssertionError: \u001b[31mFAILURE: \u001b[0mcheck True == False\n\u001b[31mtest_api.py\u001b[0m:30 in test_second_case() -> pytest_check.equal(func, res)\n\n------------------------------------------------------------\nFailed Checks: 1", "trace": "\u001b[31mFAILURE: \u001b[0mcheck True == False\n\u001b[31mtest_api.py\u001b[0m:30 in test_second_case() -> pytest_check.equal(func, res)\n\n------------------------------------------------------------\nFailed Checks: 1"}, "steps": [{"name": "second_create_project", "status": "passed", "start": 1714302365618, "stop": 1714302365633}], "parameters": [{"name": "func", "value": "True"}, {"name": "step", "value": "'second_create_project'"}, {"name": "res", "value": "False"}], "start": 1714302365618, "stop": 1714302365633, "uuid": "415b547b-17e1-4c75-bb3d-d10d16a46d93", "historyId": "348064f731d0f932800f27aeb170ca26", "testCaseId": "25139f44ccbc0b02fc34a70a40916693", "fullName": "test_api.TestAPI#test_second_case", "labels": [{"name": "story", "value": "second_test_case"}, {"name": "epic", "value": "Testing docker_allure"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestAPI"}, {"name": "host", "value": "user"}, {"name": "thread", "value": "134014-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}